force-app/main/default/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <description>This is the main object for the billing process.</description>
    <label>Bill</label>
    <nameField>
        <displayFormat>BU-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Domains/Billings.cls
/*******************************************************************************
Class Name      : Billings
Description     : Main Domain class for Bill Object
Created By      : Sebastian Torres
Created Date    : 2021-09-24  
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-09-24              Initial version
*******************************************************************************/
public inherited sharing class Billings extends ApplicationDomain {
  public Billings(List<Bill__c> bills) {
    super(bills);
  }

  //Defaulting field values on insert
  public override void onApplyDefaults() {
  }

  public void createBillFromOpportunity(
    Opportunity opp,
    fflib_ISObjectUnitOfWork uow
  ) {
    Bill__c bill = new Bill__c();
    //Add rest of fields from opp or custom metadata
    bill.amount__c = opp.Amount;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> sObjectList) {
      return new Billings(sObjectList);
    }
  }
}