force-app/main/default/objects/Support_Tier__mdt/Support_Tier__mdt.object-meta.xml
<CustomObject>
    <label>Support Tier</label>
    <pluralLabel>Support Tiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Support_Tier__mdt/fields/Allowed_Tickets__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Tickets__c</fullName>
    <label>Allowed Tickets</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Support_Tier__mdt/fields/Default_Discount__c.field-meta.xml
<CustomField>
    <fullName>Default_Discount__c</fullName>
    <label>Default Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Support_Tier__mdt/fields/Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Process__c</fullName>
    <label>Entitlement Process</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Services/AdminSupportFactory.cls
/*******************************************************************************
Class Name      : AdminSupportFactory
Description     : Factory to return the details of the selected SLA from Account
Created By      : Sebastian Torres
Created Date    : 2021-09-24
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-09-24              Initial version
*******************************************************************************/
public without sharing class AdminSupportFactory {
  public static SupportDetails getSupportDetails(String supportType) {
    if (supportType == 'No Support' || supportType == null)
      return null;
    Support_Tier__mdt support = Support_Tier__mdt.getInstance(supportType);
    if (support == null)
      return null;

    SupportDetails details = new SupportDetails();
    details.AllowedTickets = support.Allowed_Tickets__c;
    details.DefaultDiscount = support.Default_Discount__c;
    details.EntitlementProcess = support.Entitlement_Process__c;

    return details;
  }

  public class SupportDetails {
    public Decimal AllowedTickets;
    public Decimal DefaultDiscount;
    public String EntitlementProcess;
  }
}