force-app/main/default/objects/Opportunity/fields/Planned_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Date__c</fullName>
    <label>Planned Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce_Implementation</fullName>
            </value>
            <value>
                <fullName>Salesforce_Operate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillFromOppIntegrationTest.cls
@isTest
public class BillFromOppIntegrationTest {
  @isTest
  static void testBillCreationFromOpportunity() {
    Opportunity opp = new Opportunity(
      Name = 'Test Opp',
      Amount = 2400,
      StageName = 'Prospecting',
      CloseDate = Date.today(),
      Project_Type__c = 'Salesforce_Implementation',
      Planned_Start_Date__c = Date.today()
    );
    insert opp;

    Opportunity opp1 = [SELECT ID, StageName FROM Opportunity LIMIT 1];
    opp1.StageName = 'Closed Won';
    update opp1;
  }
}