force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>The object to handle async requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HandleUserPermission</fullName>
            </value>
            <value>
                <fullName>HandleUserActivation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Domains/Contacts.cls
/*******************************************************************************
Class Name      : Contacts
Description     : Main Domain class for Contact Object
Created By      : Sebastian Torres
Created Date    : 2021-09-03  
Modification Log:
------------------------------------------------------------------------------- 
Developer                   Date                   Description
--------------------------------------------------------------------------------
Sebastian                 2021-09-03              Initial version
*******************************************************************************/
public inherited sharing class Contacts extends ApplicationDomain {
  public Contacts(List<Contact> contacts) {
    super(contacts);
  }

  //Defaulting field values on insert
  public override void onApplyDefaults() {
  }

  public override void onAfterUpdate(Map<Id, sObject> existingRecords) {
    getQualifiedContactsAndUpdateUsers(
      (List<Contact>) Records,
      existingRecords
    );
  }

  public void getQualifiedContactsAndUpdateUsers(
    List<Contact> Records,
    Map<Id, sObject> existingRecords
  ) {
    Map<Id, Contact> contactsOldMap = new Map<ID, Contact>(
      (List<Contact>) existingRecords.values()
    );
    List<AsyncRequest__c> newAsyncRequests = new List<AsyncRequest__c>();
    List<String> textChangedIdsActivate = new List<ID>();
    List<String> textChangedIdsDeactivate = new List<ID>();
    for (Contact c : Records) {
      if (
        c.AccountId != null &&
        c.Active__c != contactsOldMap.get(c.id).Active__c
      ) {
        if (c.Active__c) {
          textChangedIdsActivate.add(c.Id);
          if (textChangedIdsActivate.size() > 100) {
            newAsyncRequests.add(
              new AsyncRequest__c(
                AsyncType__c = 'HandleUserActivation',
                Params__c = string.Join(textChangedIdsActivate, ',')
              )
            );
            textChangedIdsActivate.clear();
          }
        } else if (!c.Active__c) {
          textChangedIdsDeactivate.add(c.Id);
          if (textChangedIdsDeactivate.size() > 100) {
            newAsyncRequests.add(
              new AsyncRequest__c(
                AsyncType__c = 'HandleUserDeactivation',
                Params__c = string.Join(textChangedIdsDeactivate, ',')
              )
            );
            textChangedIdsDeactivate.clear();
          }
        }
      }
    }
    if (textChangedIdsActivate.size() > 0) {
      newAsyncRequests.add(
        new AsyncRequest__c(
          AsyncType__c = 'HandleUserActivation',
          Params__c = string.Join(textChangedIdsActivate, ',')
        )
      );
    }
    if (textChangedIdsDeactivate.size() > 0) {
      newAsyncRequests.add(
        new AsyncRequest__c(
          AsyncType__c = 'HandleUserDeactivation',
          Params__c = string.Join(textChangedIdsDeactivate, ',')
        )
      );
    }
    insert newAsyncRequests;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> sObjectList) {
      return new Contacts(sObjectList);
    }
  }
}