force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>The object to handle async requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Services/AsyncHandleUserDeactivation.cls
/*********************************************************************************
Class Name      : AsyncHandleUserDeactivation
Description     : Address Validation Async support class
Created By      : Sebastian Torres
Created Date    : 2021-04-14 
Modification Log: 
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-04-14              Initial version
*********************************************************************************/
public class AsyncHandleUserDeactivation extends AsyncJob {
  public override void executeAsyncProcess(AsyncRequest__c request) {
    //Checking limits
    if (!limitsAvailable())
      return;

    futureUpdateCall(request.Params__c);
  }

  @future
  static void futureUpdateCall(String params) {
    List<ID> idsAfterSplit = params.split(',');
    Set<Id> contactIds = new Set<Id>();

    for (id id : idsAfterSplit) {
      contactIds.add(id);
    }

    UserService.deactivateUserFromContact(contactIds);
  }
}